export const DEVICE_SERVICE = '9910';
export const BREATHING_SERVICE = '9920';
export const STATS_SERVICE = '9930';

export const BREATHING_MODES_CHARACTERISCTICS = '9921';
export const STATS_SERVICE_CHARACTERISTICS = '9931';
